//! bt2usb-cli - Command-line interface for the bt2usb BLE-to-USB bridge
//!
//! Communicates with the bt2usb device over a vendor HID interface
//! using COBS-framed CBOR messages.

mod commands;
mod defmt_decode;
mod logging;
#[cfg(feature = "probe")]
mod probe_rtt;
mod protocol;
mod setup_rules;
mod transport;
mod uf2;
mod write_firmware;

// Embedded firmware ELF (generated by build.rs — empty if firmware not built yet)
include!(concat!(env!("OUT_DIR"), "/embedded_elf.rs"));

use anyhow::Result;
use clap::{Parser, Subcommand};

use commands::*;
use transport::Transport;

#[derive(Parser)]
#[command(name = "bt2usb-cli", about = "Control the bt2usb BLE-to-USB bridge")]
struct Cli {
    /// HID device path to use (auto-detected if not specified)
    #[arg(short, long)]
    device: Option<String>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Show device status
    Status,

    /// Scan for BLE HID devices
    Scan {
        /// Scan duration in seconds
        #[arg(short, long, default_value = "15")]
        timeout: u64,
    },

    /// Connect to a BLE device by address
    Connect {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,

        /// Address type: 0=public, 1=random
        #[arg(short = 'k', long, default_value = "1")]
        addr_kind: u8,

        /// Device profile: 0=generic, 1=MxMaster3S, 2=FullScrollDial(8-bit), 3=FullScrollDial(16-bit, default)
        #[arg(short, long)]
        profile: Option<u8>,
    },

    /// Disconnect a device (all devices if no address given)
    Disconnect {
        /// BLE address to disconnect (omit for all)
        address: Option<String>,
    },

    /// List bonded devices
    Bonds,

    /// Clear all bonds
    ClearBonds,

    /// Clear a single bond by address
    ClearBond {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,
    },

    /// Set the profile for a bonded device
    SetProfile {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,

        /// Profile ID: 0=generic, 1=MxMaster3S, 2=FullScrollDial(8-bit), 3=FullScrollDial(16-bit, default)
        profile_id: u8,
    },

    /// Set the active device for auto-reconnect
    SetActiveDevice {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,

        /// Address type: 0=public, 1=random
        #[arg(short = 'k', long, default_value = "1")]
        addr_kind: u8,
    },

    /// Clear the active device (disable auto-reconnect)
    ClearActiveDevice,

    /// Enable auto-connect for a bonded device
    #[command(name = "set-auto-connect")]
    SetAutoConnect {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,
    },

    /// Disable auto-connect for a bonded device
    #[command(name = "clear-auto-connect")]
    ClearAutoConnect {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,
    },

    /// Auto-connect to the active device from preferences
    AutoConnect,

    /// Stream live logs from device
    Logs {
        /// Minimum log level (text mode only): 0=debug, 1=info, 2=warn, 3=error
        #[arg(short, long, default_value = "1")]
        level: u8,

        /// Duration to stream logs (seconds, 0=forever)
        #[arg(short, long, default_value = "0")]
        timeout: u64,

        /// Path to firmware ELF for defmt decoding (overrides embedded ELF)
        #[arg(long)]
        elf: Option<String>,

        /// Use legacy text log mode instead of defmt decoding
        #[arg(long)]
        text: bool,

        /// Read logs via debug probe RTT instead of USB (requires --features probe)
        #[arg(long)]
        probe: bool,
    },

    /// Show current configuration (axis multipliers)
    GetConfig,

    /// Set a configuration value
    SetConfig {
        /// Config key: scroll, pan, x, y, threshold, max_detents
        key: String,

        /// Value (percentage for multipliers, raw units for threshold/max_detents)
        value: u32,
    },

    /// Show firmware version
    Version,

    /// Restart the device
    Restart,

    /// Force re-probe the host OS (resets device into probe mode)
    Reprobe,

    /// Force a specific OS identity (skip probe on soft reset)
    #[command(name = "set-os")]
    SetOs {
        /// OS to force: auto, windows, linux, macos
        os: String,
    },

    /// Flash firmware to a Pico in BOOTSEL mode (converts embedded ELF to UF2)
    #[command(name = "write-firmware")]
    WriteFirmware {
        /// Mount path of the Pico in BOOTSEL mode (auto-detected if not specified)
        path: Option<String>,
    },

    /// Install OS-specific rules for non-root device access (udev on Linux)
    #[command(name = "setup-rules")]
    SetupRules {
        /// Remove previously installed rules instead of installing
        #[arg(long)]
        uninstall: bool,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    // Commands that don't need a device connection
    match &cli.command {
        Command::SetupRules { uninstall } => return setup_rules::cmd_setup_rules(*uninstall),
        Command::WriteFirmware { ref path } => {
            return write_firmware::cmd_write_firmware(path.as_deref())
        }
        Command::Logs {
            level,
            timeout,
            elf,
            text,
            probe,
        } => {
            // Logs handles its own connection lifecycle (wait-for-device + reconnect).
            // Try to connect now but don't fail — the log loop will retry.
            let transport = if *probe {
                None
            } else if let Some(device) = &cli.device {
                Transport::connect_to(device).ok()
            } else {
                Transport::connect().ok()
            };
            return logging::cmd_logs(transport, *level, *timeout, elf.as_deref(), *text, *probe);
        }
        _ => {}
    }

    let mut transport = if let Some(device) = &cli.device {
        Transport::connect_to(device)?
    } else {
        Transport::connect()?
    };

    match cli.command {
        Command::WriteFirmware { .. } | Command::Logs { .. } | Command::SetupRules { .. } => {
            unreachable!()
        }
        Command::Status => cmd_status(&mut transport),
        Command::Scan { timeout } => cmd_scan(&mut transport, timeout),
        Command::Connect {
            address,
            addr_kind,
            profile,
        } => cmd_connect(&mut transport, &address, addr_kind, profile),
        Command::Disconnect { address } => cmd_disconnect(&mut transport, address.as_deref()),
        Command::Bonds => cmd_bonds(&mut transport),
        Command::ClearBonds => cmd_clear_bonds(&mut transport),
        Command::ClearBond { address } => cmd_clear_bond(&mut transport, &address),
        Command::SetProfile {
            address,
            profile_id,
        } => cmd_set_profile(&mut transport, &address, profile_id),
        Command::SetActiveDevice { address, addr_kind } => {
            cmd_set_active_device(&mut transport, &address, addr_kind)
        }
        Command::ClearActiveDevice => cmd_clear_active_device(&mut transport),
        Command::SetAutoConnect { address } => cmd_set_auto_connect(&mut transport, &address, true),
        Command::ClearAutoConnect { address } => {
            cmd_set_auto_connect(&mut transport, &address, false)
        }
        Command::AutoConnect => cmd_auto_connect(&mut transport),
        Command::GetConfig => cmd_get_config(&mut transport),
        Command::SetConfig { key, value } => cmd_set_config(&mut transport, &key, value),
        Command::Version => cmd_version(&mut transport),
        Command::Restart => cmd_restart(&mut transport),
        Command::Reprobe => cmd_reprobe(&mut transport),
        Command::SetOs { os } => cmd_set_os(&mut transport, &os),
    }
}
