//! bt2usb-cli - Command-line interface for the bt2usb BLE-to-USB bridge
//!
//! Communicates with the bt2usb device over a vendor HID interface
//! using COBS-framed CBOR messages.

mod defmt_decode;
#[cfg(feature = "probe")]
mod probe_rtt;
mod protocol;
mod transport;
mod uf2;

// Embedded firmware ELF (generated by build.rs — empty if firmware not built yet)
include!(concat!(env!("OUT_DIR"), "/embedded_elf.rs"));

use anyhow::Result;
use clap::{Parser, Subcommand};
use colored::Colorize;
use std::time::Duration;

use protocol::*;
use transport::{format_address, parse_address, Message, Transport};

/// Default request timeout
const DEFAULT_TIMEOUT: Duration = Duration::from_secs(3);

#[derive(Parser)]
#[command(name = "bt2usb-cli", about = "Control the bt2usb BLE-to-USB bridge")]
struct Cli {
    /// HID device path to use (auto-detected if not specified)
    #[arg(short, long)]
    device: Option<String>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Show device status
    Status,

    /// Scan for BLE HID devices
    Scan {
        /// Scan duration in seconds
        #[arg(short, long, default_value = "15")]
        timeout: u64,
    },

    /// Connect to a BLE device by address
    Connect {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,

        /// Address type: 0=public, 1=random
        #[arg(short = 'k', long, default_value = "1")]
        addr_kind: u8,

        /// Device profile: 0=generic, 1=MxMaster3S, 2=FullScrollDial(8-bit), 3=FullScrollDial(16-bit, default)
        #[arg(short, long)]
        profile: Option<u8>,
    },

    /// Disconnect the current device
    Disconnect,

    /// List bonded devices
    Bonds,

    /// Clear all bonds
    ClearBonds,

    /// Set the profile for a bonded device
    SetProfile {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,

        /// Profile ID: 0=generic, 1=MxMaster3S, 2=FullScrollDial(8-bit), 3=FullScrollDial(16-bit, default)
        profile_id: u8,
    },

    /// Set the active device for auto-reconnect
    SetActiveDevice {
        /// BLE address (AA:BB:CC:DD:EE:FF)
        address: String,

        /// Address type: 0=public, 1=random
        #[arg(short = 'k', long, default_value = "1")]
        addr_kind: u8,
    },

    /// Clear the active device (disable auto-reconnect)
    ClearActiveDevice,

    /// Auto-connect to the active device from preferences
    AutoConnect,

    /// Stream live logs from device
    Logs {
        /// Minimum log level (text mode only): 0=debug, 1=info, 2=warn, 3=error
        #[arg(short, long, default_value = "1")]
        level: u8,

        /// Duration to stream logs (seconds, 0=forever)
        #[arg(short, long, default_value = "0")]
        timeout: u64,

        /// Path to firmware ELF for defmt decoding (overrides embedded ELF)
        #[arg(long)]
        elf: Option<String>,

        /// Use legacy text log mode instead of defmt decoding
        #[arg(long)]
        text: bool,

        /// Read logs via debug probe RTT instead of USB (requires --features probe)
        #[arg(long)]
        probe: bool,
    },

    /// Show current configuration (axis multipliers)
    GetConfig,

    /// Set a configuration value
    SetConfig {
        /// Config key: scroll, pan, x, y, threshold, max_detents
        key: String,

        /// Value (percentage for multipliers, raw units for threshold/max_detents)
        value: u32,
    },

    /// Show firmware version
    Version,

    /// Restart the device
    Restart,

    /// Force re-probe the host OS (resets device into probe mode)
    Reprobe,

    /// Force a specific OS identity (skip probe on soft reset)
    #[command(name = "set-os")]
    SetOs {
        /// OS to force: auto, windows, linux, macos
        os: String,
    },

    /// Flash firmware to a Pico in BOOTSEL mode (converts embedded ELF to UF2)
    #[command(name = "write-firmware")]
    WriteFirmware {
        /// Mount path of the Pico in BOOTSEL mode (auto-detected if not specified)
        path: Option<String>,
    },

    /// Install OS-specific rules for non-root device access (udev on Linux)
    #[command(name = "setup-rules")]
    SetupRules {
        /// Remove previously installed rules instead of installing
        #[arg(long)]
        uninstall: bool,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    // Commands that don't need a device connection
    match &cli.command {
        Command::SetupRules { uninstall } => return cmd_setup_rules(*uninstall),
        Command::WriteFirmware { ref path } => return cmd_write_firmware(path.as_deref()),
        Command::Logs {
            level,
            timeout,
            elf,
            text,
            probe,
        } => {
            // Logs handles its own connection lifecycle (wait-for-device + reconnect).
            // Try to connect now but don't fail — the log loop will retry.
            let transport = if *probe {
                None // Probe mode doesn't use USB transport
            } else if let Some(device) = &cli.device {
                Transport::connect_to(device).ok()
            } else {
                Transport::connect().ok()
            };
            return cmd_logs(transport, *level, *timeout, elf.as_deref(), *text, *probe);
        }
        _ => {}
    }

    let mut transport = if let Some(device) = &cli.device {
        Transport::connect_to(device)?
    } else {
        Transport::connect()?
    };

    match cli.command {
        Command::WriteFirmware { .. } | Command::Logs { .. } | Command::SetupRules { .. } => {
            unreachable!()
        }
        Command::Status => cmd_status(&mut transport),
        Command::Scan { timeout } => cmd_scan(&mut transport, timeout),
        Command::Connect {
            address,
            addr_kind,
            profile,
        } => cmd_connect(&mut transport, &address, addr_kind, profile),
        Command::Disconnect => cmd_disconnect(&mut transport),
        Command::Bonds => cmd_bonds(&mut transport),
        Command::ClearBonds => cmd_clear_bonds(&mut transport),
        Command::SetProfile {
            address,
            profile_id,
        } => cmd_set_profile(&mut transport, &address, profile_id),
        Command::SetActiveDevice { address, addr_kind } => {
            cmd_set_active_device(&mut transport, &address, addr_kind)
        }
        Command::ClearActiveDevice => cmd_clear_active_device(&mut transport),
        Command::AutoConnect => cmd_auto_connect(&mut transport),
        Command::GetConfig => cmd_get_config(&mut transport),
        Command::SetConfig { key, value } => cmd_set_config(&mut transport, &key, value),
        Command::Version => cmd_version(&mut transport),
        Command::Restart => cmd_restart(&mut transport),
        Command::Reprobe => cmd_reprobe(&mut transport),
        Command::SetOs { os } => cmd_set_os(&mut transport, &os),
    }
}

fn cmd_status(transport: &mut Transport) -> Result<()> {
    let (resp, _events) = transport.request_simple(CMD_GET_STATUS, DEFAULT_TIMEOUT)?;
    match resp {
        Response::Status {
            state,
            bonded_count,
            active_profile,
            active_device_set,
            active_device_address,
            battery_level,
            detected_os,
        } => {
            println!("  State:          {}", state.label().bold());
            println!(
                "  Host OS:        {}",
                protocol::detected_os_name(detected_os).bold()
            );
            println!("  Bonded devices: {bonded_count}");
            println!(
                "  Active profile: {} ({})",
                active_profile,
                profile_name(active_profile)
            );

            if active_device_set {
                println!(
                    "  Active device:  {} {}",
                    format_address(&active_device_address).bold(),
                    "(auto-connect enabled)".green()
                );
            } else {
                println!(
                    "  Active device:  {} (auto-connect disabled)",
                    "None".dimmed()
                );
            }

            let battery_str = if battery_level == 0xFF {
                "Unknown".dimmed().to_string()
            } else {
                format!("{}%", battery_level).bold().to_string()
            };
            println!("  Battery:        {battery_str}");
        }
        Response::Error { code, message } => {
            eprintln!("{} (code {code}): {message}", "Error".red());
        }
        other => {
            eprintln!("Unexpected response: {other:?}");
        }
    }
    Ok(())
}

fn cmd_scan(transport: &mut Transport, timeout_secs: u64) -> Result<()> {
    // Start scan
    let (resp, events) = transport.request_simple(CMD_START_SCAN, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;

    println!("{}", "Scanning for BLE HID devices...".cyan());
    println!();

    // Print any events that came with the response
    for evt in events {
        print_event(&evt);
    }

    // Stream events for the specified duration
    let scan_timeout = Duration::from_secs(timeout_secs);
    let mut device_count = 0u32;

    transport.stream_messages(scan_timeout, |msg| {
        if let Message::Event { cbor } = msg {
            if let Ok(evt) = decode_event(&cbor) {
                match &evt {
                    Event::ScanResult { .. } => {
                        device_count += 1;
                        print_event(&evt);
                    }
                    Event::ConnectionState { state, .. } => {
                        // Scan may have been stopped by firmware
                        if matches!(state, self::ConnectionState::Disconnected) {
                            return false;
                        }
                        print_event(&evt);
                    }
                    _ => print_event(&evt),
                }
            }
        }
        true
    })?;

    // Stop scan
    let _ = transport.request_simple(CMD_STOP_SCAN, DEFAULT_TIMEOUT);

    println!();
    println!(
        "Scan complete. {} device(s) found.",
        device_count.to_string().bold()
    );

    Ok(())
}

fn cmd_connect(
    transport: &mut Transport,
    address: &str,
    addr_kind: u8,
    profile: Option<u8>,
) -> Result<()> {
    let addr = parse_address(address)?;

    let mut cbor_buf = [0u8; 32];
    let len = encode_request_connect(&mut cbor_buf, &addr, addr_kind)
        .map_err(|_| anyhow::anyhow!("encode failed"))?;

    println!("Connecting to {}...", format_address(&addr).bold());

    if let Some(profile_id) = profile {
        let profile_name = profile_name(profile_id);
        println!("  Profile: {profile_name}");
    }

    let (resp, events) = transport.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;

    for evt in events {
        print_event(&evt);
    }

    // Stream events until we see Ready or an error
    let connect_timeout = Duration::from_secs(30);
    let mut pairing_complete = false;
    transport.stream_messages(connect_timeout, |msg| {
        if let Message::Event { cbor } = msg {
            if let Ok(evt) = decode_event(&cbor) {
                print_event(&evt);
                match &evt {
                    Event::ConnectionState { state, .. } => {
                        matches!(
                            state,
                            self::ConnectionState::Connecting
                                | self::ConnectionState::Connected
                                | self::ConnectionState::Pairing
                                | self::ConnectionState::Scanning
                        )
                    }
                    Event::PairingStatus { status } => {
                        if matches!(status, PairingState::Complete) {
                            pairing_complete = true;
                        }
                        !matches!(status, PairingState::Complete | PairingState::Failed)
                    }
                    _ => true,
                }
            } else {
                true
            }
        } else {
            true
        }
    })?;

    // If profile specified and pairing completed, update the bond profile
    if let Some(profile_id) = profile {
        if pairing_complete {
            println!("Setting profile...");
            let len = encode_request_update_bond_profile(&mut cbor_buf, &addr, profile_id)
                .map_err(|_| anyhow::anyhow!("encode failed"))?;
            let (resp, _) = transport.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
            check_ok(&resp)?;
            println!("{}", "Profile set successfully.".green());
        }
    }

    Ok(())
}

fn cmd_disconnect(transport: &mut Transport) -> Result<()> {
    let (resp, _) = transport.request_simple(CMD_DISCONNECT, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    println!("{}", "Disconnect command sent.".green());
    Ok(())
}

fn cmd_bonds(transport: &mut Transport) -> Result<()> {
    let (resp, _) = transport.request_simple(CMD_GET_BONDS, DEFAULT_TIMEOUT)?;
    match resp {
        Response::Bonds { bonds } => {
            if bonds.is_empty() {
                println!("No bonded devices.");
            } else {
                println!("Bonded devices:");
                for (i, bond) in bonds.iter().enumerate() {
                    println!(
                        "  {}. {}  \"{}\"  profile={}  kind={}",
                        i + 1,
                        format_address(&bond.address).bold(),
                        bond.name,
                        bond.profile_id,
                        if bond.addr_kind == 1 {
                            "random"
                        } else {
                            "public"
                        }
                    );
                }
            }
        }
        Response::Error { code, message } => {
            eprintln!("{} (code {code}): {message}", "Error".red());
        }
        other => {
            eprintln!("Unexpected response: {other:?}");
        }
    }
    Ok(())
}

fn cmd_clear_bonds(transport: &mut Transport) -> Result<()> {
    let (resp, _) = transport.request_simple(CMD_CLEAR_BONDS, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    println!("{}", "All bonds cleared.".green());
    Ok(())
}

fn cmd_get_config(transport: &mut Transport) -> Result<()> {
    let (resp, _) = transport.request_simple(CMD_GET_CONFIG, DEFAULT_TIMEOUT)?;
    match resp {
        Response::Config {
            scroll_mult,
            pan_mult,
            x_mult,
            y_mult,
            scroll_threshold,
            max_detents,
        } => {
            println!("Configuration:");
            println!("  scroll:        {}%", scroll_mult.to_string().bold());
            println!("  pan:           {}%", pan_mult.to_string().bold());
            println!("  x:             {}%", x_mult.to_string().bold());
            println!("  y:             {}%", y_mult.to_string().bold());
            println!("  threshold:     {}", scroll_threshold.to_string().bold());
            println!("  max_detents:   {}", max_detents.to_string().bold());
        }
        Response::Error { code, message } => {
            eprintln!("{} (code {code}): {message}", "Error".red());
        }
        other => {
            eprintln!("Unexpected response: {other:?}");
        }
    }
    Ok(())
}

fn cmd_set_config(transport: &mut Transport, key_name: &str, value: u32) -> Result<()> {
    let key = config_key_from_name(key_name).ok_or_else(|| {
        anyhow::anyhow!(
            "Unknown config key: {key_name}. Valid keys: scroll, pan, x, y, threshold, max_detents"
        )
    })?;

    let mut cbor_buf = [0u8; 16];
    let len = encode_request_set_config(&mut cbor_buf, key, value)
        .map_err(|_| anyhow::anyhow!("encode failed"))?;

    let (resp, _) = transport.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    let suffix = if key >= 4 { "" } else { "%" };
    println!("{} {} = {}{}", "Set".green(), key_name, value, suffix);
    Ok(())
}

/// Well-known mount point names for a Pico in BOOTSEL mode.
const PICO_VOLUME_NAME: &str = "RPI-RP2";

fn cmd_write_firmware(path: Option<&str>) -> Result<()> {
    if FIRMWARE_ELF.is_empty() {
        eprintln!("No firmware ELF embedded in this CLI build.");
        eprintln!("Build with `just build-all` to embed the firmware ELF.");
        std::process::exit(1);
    }

    // Convert ELF → UF2
    println!("{}", "Converting ELF to UF2...".dimmed());
    let uf2_data = uf2::elf_to_uf2(FIRMWARE_ELF)?;
    println!(
        "UF2: {} blocks, {} bytes",
        uf2_data.len() / 512,
        uf2_data.len()
    );

    // Resolve target directory
    let mount_path = match path {
        Some(p) => std::path::PathBuf::from(p),
        None => {
            println!("{}", "Auto-detecting Pico in BOOTSEL mode...".dimmed());
            match find_pico_mount() {
                Some(p) => {
                    println!("Found Pico at {}", p.display().to_string().bold());
                    p
                }
                None => {
                    eprintln!(
                        "{}: Could not find a mounted Pico ({PICO_VOLUME_NAME}).",
                        "Error".red()
                    );
                    eprintln!("Put the Pico into BOOTSEL mode (hold BOOTSEL while plugging in),");
                    eprintln!("then either re-run or specify the mount path manually:");
                    eprintln!("  bt2usb-cli write-firmware /path/to/{PICO_VOLUME_NAME}");
                    std::process::exit(1);
                }
            }
        }
    };

    // Validate mount point: must be a directory containing INFO_UF2.TXT
    if !mount_path.is_dir() {
        anyhow::bail!(
            "'{}' is not a directory. Provide the mount point of the Pico.",
            mount_path.display()
        );
    }
    if !mount_path.join("INFO_UF2.TXT").exists() {
        anyhow::bail!(
            "'{}' does not look like a Pico in BOOTSEL mode (missing INFO_UF2.TXT).",
            mount_path.display()
        );
    }

    let dest = mount_path.join("bt2usb.uf2");
    println!("Writing to {}...", dest.display().to_string().bold());
    std::fs::write(&dest, &uf2_data)?;

    println!(
        "{}",
        "Firmware written. The Pico will reboot automatically.".green()
    );
    Ok(())
}

/// Try to find a mounted Pico in BOOTSEL mode by searching common mount locations.
fn find_pico_mount() -> Option<std::path::PathBuf> {
    let candidates: Vec<std::path::PathBuf> = if cfg!(target_os = "macos") {
        vec![std::path::PathBuf::from(format!(
            "/Volumes/{PICO_VOLUME_NAME}"
        ))]
    } else if cfg!(target_os = "linux") {
        // Check /media/$USER/RPI-RP2 and /run/media/$USER/RPI-RP2
        let mut paths = Vec::new();
        if let Ok(user) = std::env::var("USER") {
            paths.push(std::path::PathBuf::from(format!(
                "/media/{user}/{PICO_VOLUME_NAME}"
            )));
            paths.push(std::path::PathBuf::from(format!(
                "/run/media/{user}/{PICO_VOLUME_NAME}"
            )));
        }
        // Also scan /media/*/RPI-RP2 in case username doesn't match
        if let Ok(entries) = std::fs::read_dir("/media") {
            for entry in entries.flatten() {
                let p = entry.path().join(PICO_VOLUME_NAME);
                if !paths.contains(&p) {
                    paths.push(p);
                }
            }
        }
        paths
    } else if cfg!(target_os = "windows") {
        // On Windows, scan drive letters for INFO_UF2.TXT
        (b'D'..=b'Z')
            .map(|c| std::path::PathBuf::from(format!("{}:\\", c as char)))
            .collect()
    } else {
        vec![]
    };

    candidates
        .into_iter()
        .find(|p| p.is_dir() && p.join("INFO_UF2.TXT").exists())
}

// ---------------------------------------------------------------------------
// setup-rules: install/uninstall OS-specific device access rules
// ---------------------------------------------------------------------------

/// udev rules file path on Linux.
const UDEV_RULES_PATH: &str = "/etc/udev/rules.d/99-bt2usb.rules";

/// Generate udev rules content for both bt2usb USB identities.
fn udev_rules_content() -> String {
    format!(
        r#"# bt2usb — allow non-root access to the BLE-to-USB bridge
# Apple MT2 mode (macOS identity)
SUBSYSTEM=="hidraw", ATTRS{{idVendor}}=="{:04x}", ATTRS{{idProduct}}=="{:04x}", MODE="0666", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{{idVendor}}=="{:04x}", ATTRS{{idProduct}}=="{:04x}", MODE="0666", TAG+="uaccess"
# Generic bt2usb mode (Linux/Windows identity)
SUBSYSTEM=="hidraw", ATTRS{{idVendor}}=="{:04x}", ATTRS{{idProduct}}=="{:04x}", MODE="0666", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{{idVendor}}=="{:04x}", ATTRS{{idProduct}}=="{:04x}", MODE="0666", TAG+="uaccess"
"#,
        transport::USB_VID_APPLE,
        transport::USB_PID_MT2,
        transport::USB_VID_APPLE,
        transport::USB_PID_MT2,
        transport::USB_VID_BT2USB,
        transport::USB_PID_BT2USB,
        transport::USB_VID_BT2USB,
        transport::USB_PID_BT2USB,
    )
}

fn cmd_setup_rules(uninstall: bool) -> Result<()> {
    match std::env::consts::OS {
        "linux" => {
            if uninstall {
                cmd_setup_rules_linux_uninstall()
            } else {
                cmd_setup_rules_linux_install()
            }
        }
        "macos" => {
            println!("{}", "No special rules are required on macOS.".green());
            println!(
                "{}",
                "HID devices are accessible to all users by default.".dimmed()
            );
            Ok(())
        }
        os => {
            eprintln!("{}: setup-rules is not supported on '{os}'.", "Error".red());
            eprintln!("This command currently supports Linux (udev rules).");
            std::process::exit(1);
        }
    }
}

fn cmd_setup_rules_linux_install() -> Result<()> {
    let rules = udev_rules_content();

    // Check for existing rules
    if std::path::Path::new(UDEV_RULES_PATH).exists() {
        if let Ok(existing) = std::fs::read_to_string(UDEV_RULES_PATH) {
            if existing == rules {
                println!("{}", "Rules are already installed and up to date.".green());
                return Ok(());
            }
        }
        println!(
            "{}",
            "Existing rules file found — it will be overwritten.".yellow()
        );
    }

    // Try direct write first; fall back to sudo
    if std::fs::write(UDEV_RULES_PATH, &rules).is_ok() {
        println!("Installed {}", UDEV_RULES_PATH.bold());
    } else {
        println!(
            "{}",
            "Root privileges required. Running with sudo...".dimmed()
        );

        // Write rules to a temp file, then sudo-copy into place
        let tmp = std::env::temp_dir().join("99-bt2usb.rules");
        std::fs::write(&tmp, &rules)
            .map_err(|e| anyhow::anyhow!("Failed to write temp file {}: {e}", tmp.display()))?;

        let status = std::process::Command::new("sudo")
            .args(["cp", &tmp.to_string_lossy(), UDEV_RULES_PATH])
            .status()
            .map_err(|e| anyhow::anyhow!("Failed to run sudo: {e}"))?;
        let _ = std::fs::remove_file(&tmp);

        if !status.success() {
            anyhow::bail!("sudo cp failed (exit code: {:?})", status.code());
        }
        println!("Installed {}", UDEV_RULES_PATH.bold());
    }

    // Reload udev rules
    println!("{}", "Reloading udev rules...".dimmed());
    let reload = std::process::Command::new("sudo")
        .args(["udevadm", "control", "--reload-rules"])
        .status();
    let trigger = std::process::Command::new("sudo")
        .args(["udevadm", "trigger"])
        .status();

    match (reload, trigger) {
        (Ok(r), Ok(t)) if r.success() && t.success() => {
            println!("{}", "udev rules reloaded successfully.".green());
        }
        _ => {
            println!(
                "{}",
                "Could not reload rules automatically. Run manually:".yellow()
            );
            println!("  sudo udevadm control --reload-rules && sudo udevadm trigger");
        }
    }

    println!();
    println!(
        "{}",
        "You may need to re-plug the device for rules to take effect.".dimmed()
    );
    Ok(())
}

fn cmd_setup_rules_linux_uninstall() -> Result<()> {
    if !std::path::Path::new(UDEV_RULES_PATH).exists() {
        println!("{}", "No rules file found — nothing to remove.".yellow());
        return Ok(());
    }

    // Try direct remove; fall back to sudo
    if std::fs::remove_file(UDEV_RULES_PATH).is_ok() {
        println!("Removed {}", UDEV_RULES_PATH.bold());
    } else {
        println!(
            "{}",
            "Root privileges required. Running with sudo...".dimmed()
        );
        let status = std::process::Command::new("sudo")
            .args(["rm", UDEV_RULES_PATH])
            .status()
            .map_err(|e| anyhow::anyhow!("Failed to run sudo: {e}"))?;
        if !status.success() {
            anyhow::bail!("sudo rm failed (exit code: {:?})", status.code());
        }
        println!("Removed {}", UDEV_RULES_PATH.bold());
    }

    // Reload udev rules
    let _ = std::process::Command::new("sudo")
        .args(["udevadm", "control", "--reload-rules"])
        .status();
    println!("{}", "udev rules reloaded.".green());
    Ok(())
}

/// Polling interval when waiting for the device to appear.
const POLL_INTERVAL: Duration = Duration::from_millis(250);

fn cmd_logs(
    transport: Option<Transport>,
    level: u8,
    timeout_secs: u64,
    elf_path: Option<&str>,
    text_mode: bool,
    probe_mode: bool,
) -> Result<()> {
    if text_mode {
        let mut t = wait_for_device(transport);
        return cmd_logs_text(&mut t, level, timeout_secs);
    }

    // Resolve ELF bytes for defmt decoding
    let (decoder, _elf_bytes) = resolve_defmt_decoder(elf_path);
    // _elf_bytes used by probe mode for RTT address extraction
    #[cfg(feature = "probe")]
    let elf_bytes = _elf_bytes;

    if probe_mode {
        #[cfg(feature = "probe")]
        {
            let decoder = match decoder {
                Some(d) => d,
                None => anyhow::bail!(
                    "--probe requires a defmt decoder. Use --elf <path> or build with `just build-all`."
                ),
            };
            return probe_rtt::cmd_logs_probe(decoder, elf_bytes, timeout_secs);
        }
        #[cfg(not(feature = "probe"))]
        anyhow::bail!(
            "--probe requires the probe feature. Build with: cargo build --package bt2usb-cli --features probe"
        );
    }

    if let Some(decoder) = decoder {
        cmd_logs_defmt(transport, decoder, timeout_secs)
    } else {
        let mut t = wait_for_device(transport);
        cmd_logs_text(&mut t, level, timeout_secs)
    }
}

/// Try to create a defmt decoder from the provided ELF path or the embedded ELF.
/// Returns the decoder (if successful) and the raw ELF bytes (for RTT address extraction).
fn resolve_defmt_decoder(
    elf_path: Option<&str>,
) -> (Option<defmt_decode::DefmtDecoder>, &'static [u8]) {
    if let Some(path) = elf_path {
        match defmt_decode::DefmtDecoder::from_elf_path(std::path::Path::new(path)) {
            Ok(d) => {
                // For --elf with --probe, we'd need the bytes for RTT address extraction.
                // The embedded ELF may still be useful for that if available.
                return (Some(d), FIRMWARE_ELF);
            }
            Err(e) => {
                eprintln!("Failed to load ELF '{}': {e:#}", path);
                return (None, FIRMWARE_ELF);
            }
        }
    }

    if !FIRMWARE_ELF.is_empty() {
        match defmt_decode::DefmtDecoder::from_elf(FIRMWARE_ELF) {
            Ok(d) => return (Some(d), FIRMWARE_ELF),
            Err(e) => {
                eprintln!(
                    "Embedded ELF ({} bytes) failed to parse: {e:#}",
                    FIRMWARE_ELF.len()
                );
                eprintln!("Run `bt2usb-cli dump-elf` to inspect.");
                return (None, FIRMWARE_ELF);
            }
        }
    }

    eprintln!("{}", "No firmware ELF embedded in this CLI build.".yellow());
    eprintln!("Use --elf <path> or --text, or rebuild with `just build-all`.");
    (None, FIRMWARE_ELF)
}

/// Block until a device is connected, returning a live transport.
/// If `existing` is already Some, returns it immediately.
fn wait_for_device(existing: Option<Transport>) -> Transport {
    if let Some(t) = existing {
        return t;
    }
    eprint!("{}", "Waiting for device...".dimmed());
    loop {
        if let Ok(t) = Transport::connect() {
            eprintln!(" {}", "connected".green());
            return t;
        }
        std::thread::sleep(POLL_INTERVAL);
    }
}

fn cmd_logs_defmt(
    mut transport: Option<Transport>,
    mut decoder: defmt_decode::DefmtDecoder,
    timeout_secs: u64,
) -> Result<()> {
    let stream_timeout = if timeout_secs == 0 {
        Duration::from_secs(86400)
    } else {
        Duration::from_secs(timeout_secs)
    };

    let mut version_checked = false;

    loop {
        // Ensure we have a connection
        let t = match &mut transport {
            Some(t) => t,
            None => {
                // Poll for device at 250ms intervals
                loop {
                    match Transport::connect() {
                        Ok(new_t) => {
                            transport = Some(new_t);
                            eprintln!(" {}", "connected".green());
                            break;
                        }
                        Err(_) => std::thread::sleep(POLL_INTERVAL),
                    }
                }
                transport.as_mut().unwrap()
            }
        };

        // Version mismatch check (once per session)
        if !version_checked {
            version_checked = true;
            if let Ok((Response::Version { version: dev_ver }, _)) =
                t.request_simple(CMD_GET_VERSION, DEFAULT_TIMEOUT)
            {
                let cli_ver = env!("CARGO_PKG_VERSION");
                if dev_ver != cli_ver {
                    eprintln!(
                        "{}: firmware version ({dev_ver}) != CLI version ({cli_ver})",
                        "Warning".yellow()
                    );
                    eprintln!(
                        "{}",
                        "defmt frames may not decode correctly. Rebuild with: just build-all"
                            .dimmed()
                    );
                }
            }
        }

        // Subscribe to defmt stream
        let subscribe_result = (|| -> Result<()> {
            let mut cbor_buf = [0u8; 16];
            let len = encode_request_subscribe_defmt(&mut cbor_buf)
                .map_err(|_| anyhow::anyhow!("encode failed"))?;
            let (resp, _) = t.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
            check_ok(&resp)
        })();

        if let Err(_e) = subscribe_result {
            // Subscribe failed (device may have disconnected during handshake)
            transport = None;
            eprint!("{}", "Waiting for device...".dimmed());
            std::thread::sleep(POLL_INTERVAL);
            continue;
        }

        eprintln!(
            "{}",
            "Streaming defmt logs... Press Ctrl+C to stop.".dimmed()
        );

        let result = t.stream_messages(stream_timeout, |msg| {
            if let Message::Event { cbor } = msg {
                if let Ok(evt) = decode_event(&cbor) {
                    match evt {
                        Event::DefmtFrame { data } => {
                            for line in decoder.feed(&data) {
                                println!("{line}");
                            }
                        }
                        other => print_event(&other),
                    }
                }
            }
            true
        });

        // Try to unsubscribe (best-effort)
        let _ = t.request_simple(CMD_UNSUBSCRIBE_DEFMT, DEFAULT_TIMEOUT);

        match result {
            Ok(()) => return Ok(()), // Clean exit (timeout or Ctrl+C)
            Err(_) => {
                transport = None;
                eprint!("{}", "Waiting for device...".dimmed());
                std::thread::sleep(POLL_INTERVAL);
            }
        }
    }
}

fn cmd_logs_text(transport: &mut Transport, level: u8, timeout_secs: u64) -> Result<()> {
    // Subscribe to text logs
    let mut cbor_buf = [0u8; 16];
    let len = encode_request_subscribe_logs(&mut cbor_buf, level)
        .map_err(|_| anyhow::anyhow!("encode failed"))?;
    let (resp, _) = transport.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;

    let level_name = log_level_name(level);
    println!("Streaming text logs (level >= {level_name})... Press Ctrl+C to stop.");
    println!();

    let stream_timeout = if timeout_secs == 0 {
        Duration::from_secs(86400)
    } else {
        Duration::from_secs(timeout_secs)
    };

    let result = transport.stream_messages(stream_timeout, |msg| {
        if let Message::Event { cbor } = msg {
            if let Ok(evt) = decode_event(&cbor) {
                print_event(&evt);
            }
        }
        true
    });

    // Unsubscribe
    let _ = transport.request_simple(CMD_UNSUBSCRIBE_LOGS, DEFAULT_TIMEOUT);

    result
}

fn cmd_version(transport: &mut Transport) -> Result<()> {
    let (resp, _) = transport.request_simple(CMD_GET_VERSION, DEFAULT_TIMEOUT)?;
    match resp {
        Response::Version { version } => {
            println!("bt2usb firmware v{version}");
        }
        Response::Error { code, message } => {
            eprintln!("{} (code {code}): {message}", "Error".red());
        }
        other => {
            eprintln!("Unexpected response: {other:?}");
        }
    }
    Ok(())
}

fn cmd_restart(transport: &mut Transport) -> Result<()> {
    println!("{}", "Restarting device...".cyan());
    let (resp, _) = transport.request_simple(CMD_RESTART, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    println!("{}", "Device restart initiated.".green());
    Ok(())
}

fn cmd_reprobe(transport: &mut Transport) -> Result<()> {
    println!(
        "{}",
        "Force re-probing host OS (device will reset)...".cyan()
    );
    let (resp, _) = transport.request_simple(CMD_FORCE_REPROBE, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    println!(
        "{}",
        "Reprobe initiated. Device will re-detect host OS and present appropriate USB identity."
            .green()
    );
    Ok(())
}

fn cmd_set_os(transport: &mut Transport, os_name: &str) -> Result<()> {
    let os_val: u8 = match os_name.to_lowercase().as_str() {
        "auto" | "probe" | "0" => 0,
        "windows" | "win" | "1" => 1,
        "linux" | "2" => 2,
        "macos" | "mac" | "3" => 3,
        _ => {
            eprintln!(
                "{}: unknown OS '{}'. Valid: auto, windows, linux, macos",
                "Error".red(),
                os_name
            );
            std::process::exit(1);
        }
    };

    let os_label = match os_val {
        0 => "Auto (probe on each reset)",
        1 => "Windows",
        2 => "Linux",
        3 => "macOS",
        _ => unreachable!(),
    };

    let mut cbor_buf = [0u8; 16];
    let cbor_len = encode_request_set_forced_os(&mut cbor_buf, os_val)
        .map_err(|_| anyhow::anyhow!("encode failed"))?;
    let (resp, _) = transport.request(&cbor_buf[..cbor_len], DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    println!("Forced OS set to: {}", os_label.bold());
    if os_val > 0 {
        println!(
            "{}",
            "Subsequent soft resets will skip OS probe and use this identity.".dimmed()
        );
        println!(
            "{}",
            "Use 'set-os auto' to re-enable automatic detection.".dimmed()
        );
    } else {
        println!(
            "{}",
            "OS will be auto-detected on each boot/reset.".dimmed()
        );
    }
    Ok(())
}

/// Check if a response is Ok, print error if not.
fn check_ok(resp: &Response) -> Result<()> {
    match resp {
        Response::Ok => Ok(()),
        Response::Error { code, message } => {
            anyhow::bail!("Device error (code {code}): {message}");
        }
        other => {
            anyhow::bail!("Unexpected response: {other:?}");
        }
    }
}

/// Pretty-print an event to stdout.
fn print_event(event: &Event) {
    match event {
        Event::ScanResult {
            address,
            name,
            rssi,
            is_hid,
            ..
        } => {
            let hid_tag = if *is_hid {
                "[HID]".green().to_string()
            } else {
                "     ".to_string()
            };
            println!(
                "  {}  {:30}  RSSI: {:4}  {}",
                format_address(address).bold(),
                format!("\"{}\"", name),
                rssi,
                hid_tag
            );
        }
        Event::ConnectionState { state, .. } => {
            let label = state.label();
            let colored_label = match state {
                self::ConnectionState::Ready => label.green().to_string(),
                self::ConnectionState::Disconnected => label.red().to_string(),
                _ => label.yellow().to_string(),
            };
            println!("  State: {colored_label}");
        }
        Event::PairingStatus { status } => {
            let msg = match status {
                PairingState::Started => "Pairing started...".yellow().to_string(),
                PairingState::KeysExchanged => "Keys exchanged".yellow().to_string(),
                PairingState::Complete => "Pairing complete!".green().to_string(),
                PairingState::Failed => "Pairing FAILED".red().to_string(),
            };
            println!("  {msg}");
        }
        Event::Log { level, message } => {
            let level_str = log_level_name(*level);
            let colored = match level {
                0 => format!("[{level_str}]").dimmed().to_string(),
                1 => format!("[{level_str}]").blue().to_string(),
                2 => format!("[{level_str}]").yellow().to_string(),
                _ => format!("[{level_str}]").red().to_string(),
            };
            println!("  {colored} {message}");
        }
        Event::BondStored {
            address,
            profile_id,
        } => {
            let profile = profile_name(*profile_id);
            println!(
                "  {} Bond stored for {} (profile: {profile})",
                "OK".green(),
                format_address(address).bold()
            );
        }
        Event::BatteryLevel { level } => {
            println!("  Battery: {}%", level.to_string().bold());
        }
        Event::DefmtFrame { data } => {
            println!(
                "  [defmt] {} raw bytes (use defmt mode to decode)",
                data.len()
            );
        }
    }
}

fn cmd_set_profile(transport: &mut Transport, address: &str, profile_id: u8) -> Result<()> {
    let addr = parse_address(address)?;
    let profile = profile_name(profile_id);

    println!(
        "Setting profile for {} to {}...",
        format_address(&addr).bold(),
        profile.bold()
    );

    let mut cbor_buf = [0u8; 32];
    let len = encode_request_update_bond_profile(&mut cbor_buf, &addr, profile_id)
        .map_err(|_| anyhow::anyhow!("encode failed"))?;

    let (resp, _) = transport.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;

    println!("{}", "Profile updated successfully.".green());
    Ok(())
}

fn cmd_set_active_device(transport: &mut Transport, address: &str, addr_kind: u8) -> Result<()> {
    let addr = parse_address(address)?;

    println!(
        "Setting active device to {}...",
        format_address(&addr).bold()
    );

    let mut cbor_buf = [0u8; 32];
    let len = encode_request_set_active_device(&mut cbor_buf, &addr, addr_kind)
        .map_err(|_| anyhow::anyhow!("encode failed"))?;

    let (resp, _) = transport.request(&cbor_buf[..len], DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;

    println!("{}", "Active device set.".green());
    Ok(())
}

fn cmd_clear_active_device(transport: &mut Transport) -> Result<()> {
    let (resp, _) = transport.request_simple(CMD_CLEAR_ACTIVE_DEVICE, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;
    println!("{}", "Active device cleared.".green());
    Ok(())
}

fn cmd_auto_connect(transport: &mut Transport) -> Result<()> {
    println!("{}", "Auto-connecting to active device...".cyan());

    let (resp, events) = transport.request_simple(CMD_AUTO_CONNECT, DEFAULT_TIMEOUT)?;
    check_ok(&resp)?;

    for evt in events {
        print_event(&evt);
    }

    // Stream events until connected
    let connect_timeout = Duration::from_secs(30);
    transport.stream_messages(connect_timeout, |msg| {
        if let Message::Event { cbor } = msg {
            if let Ok(evt) = decode_event(&cbor) {
                print_event(&evt);
                match &evt {
                    Event::ConnectionState { state, .. } => {
                        matches!(
                            state,
                            self::ConnectionState::Connecting
                                | self::ConnectionState::Connected
                                | self::ConnectionState::Pairing
                                | self::ConnectionState::Scanning
                        )
                    }
                    _ => true,
                }
            } else {
                true
            }
        } else {
            true
        }
    })?;

    Ok(())
}

/// Get profile name from ID
fn profile_name(id: u8) -> &'static str {
    match id {
        0 => "Generic",
        1 => "MX Master 3S",
        2 => "Full Scroll Dial",
        3 => "Full Scroll Dial 16-bit",
        _ => "Unknown",
    }
}
