name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always
  DEFMT_LOG: info

jobs:
  firmware-lint:
    name: Firmware Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust toolchain
        run: rustup show

      - uses: extractions/setup-just@v2

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Download CYW43 firmware
        run: just download-firmware

      - name: Lint
        run: just lint

  firmware-build:
    name: Firmware Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust toolchain
        run: rustup show

      - uses: extractions/setup-just@v2

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Download CYW43 firmware
        run: just download-firmware

      - name: Build
        run: just build release

  cli-lint:
    name: CLI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Install system dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Lint
        run: |
          cargo fmt --package bt2usb-cli --check
          cargo clippy --package bt2usb-cli -- -D warnings

  cli-build:
    name: CLI Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Install system dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Build
        run: cargo build --package bt2usb-cli --release
